name: Generate Contributors

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate CONTRIBUTORS.md
        run: |
          curl -s "https://api.github.com/repos/${{ github.repository }}/contributors" | \
          jq -r '.[] | "- " + .login + " (" + .html_url + ")"' > CONTRIBUTORS.md

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CONTRIBUTORS.md
          git commit -m "Update CONTRIBUTORS.md" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main

