name: Generate Contributors

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate contributors file
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/contributors" \
          | jq -r '.[] | "- " + .login + " (" + .html_url + ")"' > CONTRIBUTORS.md

      - name: Set Git remote to use PAT (must be after checkout)
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add CONTRIBUTORS.md
          git commit -m "Update CONTRIBUTORS.md" || echo "No changes to commit"
          git push origin main

